theme: jekyll-theme-minimal
title: Christine Allen-Blanchette
logo: /assets/img/logo.png
show_downloads: false
collections:
  gnn:
    type: reading
    output: true
  courses:
    type: course
    output: true

